import '../components/style.css'
import '../components/header.css'
import '../components/nav.css'
import '../components/hero.css'
import '../components/about.css'
import '../components/skills.css'
import '../components/training-work.css'
import '../components/work.css'
import '../components/footer.css'
import '../components/util/util.css'

